services:
  otel-collector:
    image: otel/opentelemetry-collector:0.93.0
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    volumes:
      - ./configs/otelcol.yaml:/etc/otelcol/config.yaml:ro

  prometheus:
    image: prom/prometheus:v2.45.3
    ports:
      - 9090:9090
    volumes:
      - ./configs/prometheus.yaml:/etc/prometheus/prometheus.yml:ro

  zipkin:
    image: openzipkin/zipkin:3.0.6
    ports:
      - 9411:9411

  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      - ./configs/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
